### ISSUE TITLE
Fix publish-docs

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zstash#206]
Fix `publish-docs` in the workflow. `ImportError: cannot import name 'environmentfilter' from 'jinja2' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jinja2/__init__.py)` appears in https://github.com/E3SM-Project/zstash/runs/5795869500?check_suite_focus=true. This issue was introduced with the merging of #205.

**Comment by forsyth2** [comment]
@tomvothecoder I don't know why this didn't happen with https://github.com/E3SM-Project/e3sm_diags/pull/576 and https://github.com/E3SM-Project/e3sm_diags/actions. Because in #205 `zstash` was upgraded from an older version than E3SM Diags was at?

**Comment by tomvothecoder** [comment]
I think you are right. `zstash` was using `black=20.8b1` in `pre-commit`, so it probably didn't contain the same bug as `black=22.1.0`.

For this specific issue, `jinja2` needs to be pinned < 3.1. 
Related issues
- https://github.com/readthedocs/readthedocs.org/issues/9038
- https://github.com/sphinx-doc/sphinx/issues/10291#issuecomment-1078046986

Pin locations:
- https://github.com/E3SM-Project/zstash/blob/3c75ea5f90caf98b6dbd4088d22d1e0d42e5f968/.github/workflows/build_workflow.yml#L84
- https://github.com/E3SM-Project/zstash/blob/3c75ea5f90caf98b6dbd4088d22d1e0d42e5f968/.github/workflows/release_workflow.yml#L40
- https://github.com/E3SM-Project/zstash/blob/3c75ea5f90caf98b6dbd4088d22d1e0d42e5f968/conda/dev.yml#L21-L25
  - Add `jinja2` to `dev.yml` dependencies

**Comment by forsyth2** [comment]
@tomvothecoder Looks like the fixes in #207 didn't work: https://github.com/E3SM-Project/zstash/runs/5821359209?check_suite_focus=true fails with:
```
Run pip install sphinx==3.5.1 sphinx_rtd_theme==0.5.1 sphinx-multiversion==0.2.4 docutils==0.16 jinja2<3.1
  pip install sphinx==3.5.1 sphinx_rtd_theme==0.5.1 sphinx-multiversion==0.2.4 docutils==0.16 jinja2<3.1
  shell: /usr/bin/bash -l {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.12/x64/lib
/home/runner/work/_temp/757fff76-faa8-4d7a-9725-b4631e956582.sh: line 1: 3.1: No such file or directory
Error: Process completed with exit code 1.
```

**Comment by tomvothecoder** [comment]
@forsyth2 To denote version ranges with `pip`, you have to put the package in quotations.

https://stackoverflow.com/questions/8795617/how-to-pip-install-a-package-with-min-and-max-version-range

In this case, it would be `pip install sphinx==3.5.1 sphinx_rtd_theme==0.5.1 sphinx-multiversion==0.2.4 docutils==0.16 "jinja2<3.1"`.

**Comment by forsyth2** [comment]
@tomvothecoder Thanks, that fixed it!
